### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by TheOddler** [NorfairKing/swop#108]
Integer a1 = 100;
Integer a2 = 100;
System.out.println(a1 == a2);   // true

Integer b1 = new Integer(100);
Integer b2 = new Integer(100);
System.out.println(b1 == b2);   // false

Integer c1 = 150;
Integer c2 = 150;
System.out.println(c1 == c2);   // false

http://ideone.com/EYAoON

Duuude!, Java is weird. Blijkbaar heeft die cashed waarden voor ints tussen -128 en 127, dus als die auto-boxed worden dan gebruikt die die cashed versies. Fucking Java, Java is een issue.

**Comment by NorfairKing** [comment]
Google is met zo'n dingen bezig, FYI.
Of toch de preliminaries <- google now.

Knowledge representation, natural language processing en voice recognition.
