### ISSUE TITLE
TIS GEDAAN FUCKERS!

### ISSUE THREAD

**Issue by TheOddler** [NorfairKing/swop#109]
En hoe ging het bij jullie? Waren ze tevreden met jullie uitbreiding? :D

**Comment by NorfairKing** [comment]
Da's geen issue. Eerste deel ging mij niet goed af. Tweede deel wel.

**Comment by TheOddler** [comment]
True, niet echt een issue :P 
Het deel met de expertises? Daar heb ik gwn een nieuwe resourcetype van gemaakt, en de dev zijn "isOfType" override om er meerdere te accepteren.

**Comment by MichielDerhaeg** [comment]
@TheOddler omg gij hebt exact hetzelfde gedaan als mij met expertises

**Comment by NorfairKing** [comment]
Bij expertise heb ik da een beetje verfuckt. Wou decorator gebruiken ma swat.
BIj de visits heb ik ervoor gezorgd dat alle resources op bezoek konden (niet enkel devs) met een proxy. (en gewoon een planning maken voor een taak 'bezoek aan ander branchoffice')

**Comment by jdewaen** [comment]
Kheb voor expertise een value klasse gemaakt die een expertise voorstelt en een ExpertiseRequirement ingevoerd. Requirement is nu dus een abstracte superklasse voor ExpertiseRequirement en ResourceRequirement.

Voor visits hebs ik User management naar Company niveau verplaatst. Users hebben een default BranchOffice en een set van Visit objecten die een BranchOffice en een Period bevatten. Bij het checken waar een user op een tijdstip/period is, checkt ge gewoon de lijst van visits voor een match en anders wordt de default gereturned. Bij nader inzien had ik dit ook op Resource niveau kunnen doen zoals Syd. Ik dacht eerst aan iets Delegation-achtig zoals Syd heeft gedaan maar het leek me semantisch iets mooier op mijn manier. Er wordt letterlijk aan de Developer gevraagt "Waar zijt gij tussen dan en dan?" en die Developer checkt zijn agenda om een antwoord te geven.

Ik heb precies wat meer klasses gebruikt dan jullie voor mijn oplossingen ipv de huidige systemen te jury-riggen. Anyway, we hadden "geluk" dat we zo'n flexibele basis hadden om vanaf te vertrekken.

**Comment by TheOddler** [comment]
Dat klinkt ook als een goede manier :P  Onze basis was idd goed, dus was eenvoudig aan te passen, op verschillende goede manieren zo blijkt :D 

Wat hadden ze bij jullie als vragen? Bij mij vroegen ze gwn nix nadat ik mijn uitleg gedaan had, maar ze zeiden dat dat een goed teken was, dus ikke happy :dancer:

**Comment by jdewaen** [comment]
Bij mij vroeg er nog nen assistent (den andere) hoe het zat met cohesion ivm men Company klasse die nu echt wel veel moet doen. Ik zei dat dat inderdaad een knelpunt was, maar dat we daar in onze code al oplossingen voor hadden door functionaliteit te delegeren naar andere klasses zoals PlanningDepartment, DelegationOffice, etc. De functionaliteit blijft zo dus mooi verdeeld in klasses met hoge cohesie, ookal is dit op domein niveau niet goed zichtbaar.

Aan de lichaamstaal van de prof en Gijs te zien waren ze precies wel tevreden met mijn uitleg.

**Comment by TheOddler** [comment]
Ah kei goe :D

**Comment by jdewaen** [comment]
BTW wat voor diagrammen hadden jullie? Ik heb 1 domein model getekent en 3 sequence diagrammen (create task, plan task en visit) + ik was begonnen aan de "checks" bij het plannen in sequence diagrammen te steken voor de zekerheid.

**Comment by TheOddler** [comment]
Ik heb het domain uitgebreid, gwn er bij op getekend, en het zelfde voor da groot class-diagram. Dan zo een paar sequence, ik denk 2 of 3. Niet zo heel veel dus, maar genoeg om alles wak wou zeggen duidelijk te maken.

Vroegen ze bij jullie nog om zo graps en/of een pattern uit te leggen? Ze waren precies al blij als je een patterns gebruikte in u uitbreiding, en dan was dat genoeg bij mij.

**Comment by TheOddler** [comment]
En, hebben jullie de puntjes ook al gekregen? Hoe was het bij jullie?

**Comment by NorfairKing** [comment]
Nowp we krijgen die pas overmorgen tenzij we buizen/toleranties hebben.

**Comment by TheOddler** [comment]
Amai lame, waarom dan pas?

**Comment by NorfairKing** [comment]
Omdat ze ons de practische applicaties van een Halting probleem willen tonen.

**Comment by NorfairKing** [comment]
Religie 11
Analyse 11 (dus 16 op't examen :D)
Kansrekenen 12
CN 14
SWOP 17
PNO 19

**Comment by TheOddler** [comment]
Niice :D 
Proficiat!

Mijn punten waren:
Fundamenten vd inf: 16
Gegevensstructures en algos: 17
SWOP: 17
Netwerken: 16
Gegevensbanken: 15
Numeriek Wiskunde: 16

**Comment by TheOddler** [comment]
Amai, wat een tijden seg
