### ISSUE TITLE
Presentatie voorbereiden

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/swop#60]

**Comment by NorfairKing** [comment]
I have made the script! 
Doe maar eens `make all` en ge kijken bij `presentations/iteration3` :D

**Comment by NorfairKing** [comment]
da zijn wss wel teveel diagrammen dus ge kunt best in `diagrams/class_diagrams` enkel `make class_diagrams` doen, en gewoon make bij derest van de diagrams. Het presentatie script gaat die dan wel zoeken als ge `make` doet in `presentations/iteration3`.

**Comment by TheOddler** [comment]
Wat zou het moeten doen? Want het werkt niet bij mij precies. Ik heb gewoon in de root "make all" gedaan. (En ook eens bij de diagrams, en ook bij de presentations/it3.)

**Comment by NorfairKing** [comment]
open `presentations/iteration3/iteration3.pdf`

**Comment by NorfairKing** [comment]
Did you even fetch `master`? :p

**Comment by TheOddler** [comment]
Aaaah, nope :p zat op development :P Checking now :D

**Comment by TheOddler** [comment]
"make all" in root doet nen hoop werk, maar dan krijg ik pfd zonder afbeeldingen in.
"make" in de 'presentations/iteration3' folder geeft een error :( edit: error: http://pastebin.com/pMTfFDSr

Khad zelf ook wel al een pdfke gemaakt met alle diagrammakes in die ik dacht nuttig te zijn, voor zij die niet zelf willen builden: https://www.dropbox.com/s/0zlonxxji3vd0hh/Diagrams.pdf?dl=0 ;)

**Comment by NorfairKing** [comment]
Hmm, bij mij geen probleem. Ge moet eerst de diagrammen builden in `diagrams` endan pas de presentatie.
